# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadingWindow_v01.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie


class Ui_LoadingWindow(object):
    def setupUi(self, MethodWindow):
        MethodWindow.setObjectName("MethodWindow")
        MethodWindow.resize(431, 410)
        self.centralwidget = QtWidgets.QWidget(MethodWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(30, 30, 30);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.loadingFrame = QtWidgets.QFrame(self.frame)
        self.loadingFrame.setMaximumSize(QtCore.QSize(300, 200))
        self.loadingFrame.setStyleSheet("QFrame{\n"
"background-color: rgb(40,40,40);\n"
"}")
        self.loadingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loadingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loadingFrame.setObjectName("loadingFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.loadingFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleLabel = QtWidgets.QLabel(self.loadingFrame)
        self.titleLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.titleLabel)
        self.label_2 = QtWidgets.QLabel(self.loadingFrame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        # self.movie = QMovie("C:/Users/fabri_000/Documents/_Pesquisas TCC/Bioinformática Python/gui-pyqt5/images/loading_dna02.gif")
        # self.movie.setScaledSize(2)
        # self.label_2.setMovie(self.movie)
        # self.movie.start()

        self.verticalLayout_2.addWidget(self.label_2)
        self.gridLayout.addWidget(self.loadingFrame, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        MethodWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MethodWindow)
        QtCore.QMetaObject.connectSlotsByName(MethodWindow)

    def retranslateUi(self, MethodWindow):
        _translate = QtCore.QCoreApplication.translate
        MethodWindow.setWindowTitle(_translate("MethodWindow", "MainWindow"))
        self.titleLabel.setText(_translate("MethodWindow", "Carregando"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MethodWindow = QtWidgets.QMainWindow()
    ui = Ui_MethodWindow()
    ui.setupUi(MethodWindow)
    MethodWindow.show()
    sys.exit(app.exec_())
